apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: cast-service
  name: cast-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cast-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: cast-service
    spec:
      containers:
        - args:
            - uvicorn
            - app.main:app
            - --reload
            - --host
            - 0.0.0.0
            - --port
            - "8000"
          env:
            - name: DATABASE-URI
              value: postgresql://cast-db-username:cast-db-password@cast-db/cast-db-dev
          image: cast-service
          name: cast-service
          ports:
            - containerPort: 8000
          resources: {}
          volumeMounts:
            - mountPath: /app/
              name: cast-service-claim0
      restartPolicy: Always
      volumes:
        - name: cast-service-claim0
          persistentVolumeClaim:
            claimName: cast-service-claim0
status: {}
