apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: cast-db
  name: cast-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cast-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: cast-db
    spec:
      containers:
        - env:
            - name: POSTGRES-DB
              value: cast-db-dev
            - name: POSTGRES-PASSWORD
              value: cast-db-password
            - name: POSTGRES-USER
              value: cast-db-username
          image: postgres:12.1-alpine
          name: cast-db
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data/
              name: postgres-data-cast
      restartPolicy: Always
      volumes:
        - name: postgres-data-cast
          persistentVolumeClaim:
            claimName: postgres-data-cast
status: {}
